import { Component, OnInit } from '@angular/core';
import { Input } from '@angular/core';  /** We added this to import the phone prices */
import { Output, EventEmitter } from '@angular/core'; /** We have added this so that your "notify-me" button can actually do something */

/** This indicates that the following class is a component. It provides metadata about the component, 
 * including its templates, styles, and a selector. The selector is used to identify the component. The selector 
 * is the name you give the Angular component when it is rendered as an HTML element on the page. 
By convention, Angular component selectors begin with the prefix app-, followed by the component name.
The template and style filenames. These reference the other two files generated for you. */
@Component({
  selector: 'app-product-alerts',
  templateUrl: './product-alerts.component.html',
  styleUrls: ['./product-alerts.component.css']
})
export class ProductAlertsComponent implements OnInit {


  /** The Input decorator indicates that the property value will be passed in from the component's parent (in this case, the product list component). */
  @Input() product;
  @Output() notify = new EventEmitter();     /** This is added to let our notify-me button actually do something */     
  constructor() { }

  ngOnInit() {
  }

}


/**
 


This is the code that was autogenerated for the new component: 
  
 
 import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-product-alerts',
  templateUrl: './product-alerts.component.html',
  styleUrls: ['./product-alerts.component.css']
})
export class ProductAlertsComponent implements OnInit {

  constructor() { }

  ngOnInit() {
  }

}
 
 

 */




